spring:
  application:
    name: heythere-user-server
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

cloud:
  aws:
    credentials:
      accessKey: AKIAJF2FHSSU7QJJMHXA
      secretKey: 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
    s3:
      bucket: heythere-file-store
    region:
      static: ap-northeast-2
    stack:
      auto: false

