spring:
  application:
    name: heythere-user-server
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
